// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package vehicle

import (
	"parkin-ai-system/api/vehicle"
)

type ControllerVehicle struct{}

func NewVehicle() vehicle.IVehicleVehicle {
	return &ControllerVehicle{}
}
