// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package parking_lot

import (
	"parkin-ai-system/api/parking_lot"
)

type ControllerParkingLot struct{}

func NewParkingLot() parking_lot.IParkingLotParkingLot {
	return &ControllerParkingLot{}
}
