// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package parking_slot

import (
	"parkin-ai-system/api/parking_slot"
)

type ControllerParking_slot struct{}

func NewParking_slot() parking_slot.IParkingSlotParking_slot {
	return &ControllerParking_slot{}
}
