// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// apiTokensDao is the data access object for the table api_tokens.
// You can define custom methods on it to extend its functionality as needed.
type apiTokensDao struct {
	*internal.ApiTokensDao
}

var (
	// ApiTokens is a globally accessible object for table api_tokens operations.
	ApiTokens = apiTokensDao{internal.NewApiTokensDao()}
)

// Add your custom methods and functionality below.
