// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// othersServiceDao is the data access object for the table others_service.
// You can define custom methods on it to extend its functionality as needed.
type othersServiceDao struct {
	*internal.OthersServiceDao
}

var (
	// OthersService is a globally accessible object for table others_service operations.
	OthersService = othersServiceDao{internal.NewOthersServiceDao()}
)

// Add your custom methods and functionality below.
