// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// othersServiceOrdersDao is the data access object for the table others_service_orders.
// You can define custom methods on it to extend its functionality as needed.
type othersServiceOrdersDao struct {
	*internal.OthersServiceOrdersDao
}

var (
	// OthersServiceOrders is a globally accessible object for table others_service_orders operations.
	OthersServiceOrders = othersServiceOrdersDao{internal.NewOthersServiceOrdersDao()}
)

// Add your custom methods and functionality below.
