// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// parkingLotReviewsDao is the data access object for the table parking_lot_reviews.
// You can define custom methods on it to extend its functionality as needed.
type parkingLotReviewsDao struct {
	*internal.ParkingLotReviewsDao
}

var (
	// ParkingLotReviews is a globally accessible object for table parking_lot_reviews operations.
	ParkingLotReviews = parkingLotReviewsDao{internal.NewParkingLotReviewsDao()}
)

// Add your custom methods and functionality below.
