// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// parkingLotImagesDao is the data access object for the table parking_lot_images.
// You can define custom methods on it to extend its functionality as needed.
type parkingLotImagesDao struct {
	*internal.ParkingLotImagesDao
}

var (
	// ParkingLotImages is a globally accessible object for table parking_lot_images operations.
	ParkingLotImages = parkingLotImagesDao{internal.NewParkingLotImagesDao()}
)

// Add your custom methods and functionality below.
