// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// parkingOrdersDao is the data access object for the table parking_orders.
// You can define custom methods on it to extend its functionality as needed.
type parkingOrdersDao struct {
	*internal.ParkingOrdersDao
}

var (
	// ParkingOrders is a globally accessible object for table parking_orders operations.
	ParkingOrders = parkingOrdersDao{internal.NewParkingOrdersDao()}
)

// Add your custom methods and functionality below.
