// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// parkingLotsDao is the data access object for the table parking_lots.
// You can define custom methods on it to extend its functionality as needed.
type parkingLotsDao struct {
	*internal.ParkingLotsDao
}

var (
	// ParkingLots is a globally accessible object for table parking_lots operations.
	ParkingLots = parkingLotsDao{internal.NewParkingLotsDao()}
)

// Add your custom methods and functionality below.
