// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// parkingSlotsDao is the data access object for the table parking_slots.
// You can define custom methods on it to extend its functionality as needed.
type parkingSlotsDao struct {
	*internal.ParkingSlotsDao
}

var (
	// ParkingSlots is a globally accessible object for table parking_slots operations.
	ParkingSlots = parkingSlotsDao{internal.NewParkingSlotsDao()}
)

// Add your custom methods and functionality below.
