// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// vehiclesDao is the data access object for the table vehicles.
// You can define custom methods on it to extend its functionality as needed.
type vehiclesDao struct {
	*internal.VehiclesDao
}

var (
	// Vehicles is a globally accessible object for table vehicles operations.
	Vehicles = vehiclesDao{internal.NewVehiclesDao()}
)

// Add your custom methods and functionality below.
