// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"parkin-ai-system/internal/dao/internal"
)

// walletTransactionsDao is the data access object for the table wallet_transactions.
// You can define custom methods on it to extend its functionality as needed.
type walletTransactionsDao struct {
	*internal.WalletTransactionsDao
}

var (
	// WalletTransactions is a globally accessible object for table wallet_transactions operations.
	WalletTransactions = walletTransactionsDao{internal.NewWalletTransactionsDao()}
)

// Add your custom methods and functionality below.
