// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package other_service_orders

import (
	"parkin-ai-system/api/other_service_orders"
)

type ControllerOther_service_orders struct{}

func NewOther_service_orders() other_service_orders.IOtherServiceOrdersOther_service_orders {
	return &ControllerOther_service_orders{}
}
