// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package others_service

import (
	"parkin-ai-system/api/others_service"
)

type ControllerOthers_service struct{}

func NewOthers_service() others_service.IOthersServiceOthers_service {
	return &ControllerOthers_service{}
}
