// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package wallet_transaction

import (
	"parkin-ai-system/api/wallet_transaction"
)

type ControllerWallet_transaction struct{}

func NewWallet_transaction() wallet_transaction.IWalletTransactionWallet_transaction {
	return &ControllerWallet_transaction{}
}
