// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notification

import (
	"parkin-ai-system/api/notification"
)

type ControllerNotification struct{}

func NewNotification() notification.INotificationNotification {
	return &ControllerNotification{}
}
